Software: Maya
Version:  2018
Exec: 'C:/Program Files/Autodesk/Maya2018/bin/maya.exe'

Env:
    - name: MAYA_UI_LANGUAGE
      value: en_US
      mode: over
    
    - name: MAYA_DISABLE_CLIC_IPM
      value: '1'
      mode: over
      
    - name: PYTHONPATH
      value: 'D:/repo/TDClass2_Case/shadingIO'
      mode: pre
    
    - name: MAYA_SCRIPT_PATH
      value: 'D:/repo/TDClass2_Case/shadingIO'
      mode: pre
    
    - name: MAYA_MODULE_PATH
      value: 'D:/repo/TDClass2_Case/shadingIO'
      mode: pre